// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsmUPg2plkJS86sFkXU-QkJttJJcOj8dw',
    appId: '1:166281611781:web:5090b4106e97e08931aa6c',
    messagingSenderId: '166281611781',
    projectId: 'vrinda-cloud-kitchen',
    authDomain: 'vrinda-cloud-kitchen.firebaseapp.com',
    storageBucket: 'vrinda-cloud-kitchen.firebasestorage.app',
    measurementId: 'G-71YP1K3ETE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWEKXSvzY2bMStntZKoGmGh0W6Pa7YUXM',
    appId: '1:166281611781:android:9fcef8e41977b73931aa6c',
    messagingSenderId: '166281611781',
    projectId: 'vrinda-cloud-kitchen',
    storageBucket: 'vrinda-cloud-kitchen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Yoto23-j7Syika8dy6-wT8HEu6TqpTY',
    appId: '1:166281611781:ios:a04ec6c6f376611731aa6c',
    messagingSenderId: '166281611781',
    projectId: 'vrinda-cloud-kitchen',
    storageBucket: 'vrinda-cloud-kitchen.firebasestorage.app',
    iosClientId: '166281611781-1u3uppe5erqoeflgo2ukpv73kqmid3i6.apps.googleusercontent.com',
    iosBundleId: 'com.vrindopnishad.foodyVrinda',
  );
}
